
@url = threefold.grid.reservation
threebot_id* = ""         #the user who bought the capacity
payment_secret = ""       #when time is there for renewal the farmer robot will ask the 3bot for payment, needs this secret
description = ""
error = ""

mru_nr = 0 (F)            #nr of units reserved
cru_nr = 0 (F)
sru_nr = 0 (F)
hru_nr = 0 (F)
mru_price = 0 (N)         #price in chosen currency for this unit when reservation started, is price per period
cru_price = 0 (N)
sru_price = 0 (N)
hru_price = 0 (N)

date_start* = 0 (D)       #date when the reservation started
date_end* = 0 (D)         #calculated out of nr of periods, or can be a fixed time
period = 0 (I)            #duration of period in nr of hours, 1 means 1 hour, 24 means 1 day, ...
period_nr = 0 (I)         #nr of periods this reservation has been agreed for

state* = ""                #ACTIVE, SUSPENDED, ERROR, INIT  (init is for start)

node_id* = 0 (I)          #node on which the reservation has been done
node_service_id = "" (S)  #id in which the farmer can ask for deletion of the service, no access only deletion

payments = (LO) !threefold.grid.payment


@url = threefold.grid.payment
transactionid = ""        #transaction id in the blockchain
datetime = 0 (D)          #time when payment was done
tft_nr = 0 (F)            #amounts of tokens paid

zrobot_service_secret = ""       #secret as returned by the zero node robot


#TODO:*1 for the specs of VM/ZDB/...